imagenet_templates = [
    "photo of {}.",
    "hight quality photo of {}.",
    "a photo of {}.",
    "image of {}.",
    "an image of {}.",
    "high quality image of {}.",
    "a high quality image of {}.",
    "the {}.",
    "a {}.",
    "{}.",
    "{}",
    "{}!",
    "{}...",
]